name = "psi"
license = "MIT"
licenselink = "https://github.com/andrejusk/hugo-psi-theme/blob/master/LICENSE.md"
description = "andrejus.uk website specific theme"
homepage = "https://andrejus.uk"
tags = ["clean", "fast", "responsive", "typography", "minimalistic"]
features = ["flexible", "fast", "highlights", "progressive images"]
min_version = 0.40

[author]
  name = "Andrejus Kostarevas"
  homepage = "https://andrejus.uk"
  repo = "https://github.com/andrejusk/hugo-psi-theme"

[original]
    name = "Gökmen Görgen"
    homepage = "https://gokmengorgen.net"
    repo = "https://github.com/gkmngrgn/hugo-alageek-theme"
